version: 2
project_name: kubewatch

before:
  hooks:
    - go mod download

builds:
  - id: kubewatch
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - openbsd
      - android
    goarch:
      - amd64
      - arm
      - arm64
      - loong64
      - ppc64le
      - s390x
    goarm:
      - "5"
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.revision={{ .ShortCommit }}"
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64
      - goos: android
        goarch: amd64
      - goos: android
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - non-existent*

release:
  github:
    owner: Reggles44
    name: kubewatch
  prerelease: auto
  name_template: "{{ .Version }}"

snapshot:
  version_template: "{{ .Version }}-devel"

changelog:
  sort: asc
  filters:
    exclude:
      - README
      - test
